CREATE TABLE SKYROOF.USER_TABLE
(
    USER_ID       NUMBER(19)   NOT NULL PRIMARY KEY,
    USERNAME      VARCHAR2(50) NOT NULL,
    PASSWORD      VARCHAR2(60) NOT NULL,
    ROLE          VARCHAR2(50)
        CONSTRAINT UK_USER_TABLE_USERNAME
            UNIQUE,
    CREATION_DATE TIMESTAMP(6) NOT NULL
);

CREATE TABLE SKYROOF.PROJECT
(
    PROJECT_ID    NUMBER(19)    NOT NULL PRIMARY KEY,
    TITLE         VARCHAR2(150) NOT NULL,
    DESCRIPTION   VARCHAR2(2000),
    CREATION_DATE TIMESTAMP(6)  NOT NULL,
    IS_DELETED    NUMBER(1),
    OWNER_ID      NUMBER(19)    NOT NULL
        CONSTRAINT FK_PROJECT_OWNER
            REFERENCES SKYROOF.USER_TABLE
);

CREATE TABLE SKYROOF.PROJECT_COLLABORATORS
(
    FK_PROJECT NUMBER(19) NOT NULL
        CONSTRAINT FK_PROJECT_COLLABORATORS_PROJECT
            REFERENCES SKYROOF.PROJECT,
    FK_USER    NUMBER(19) NOT NULL
        CONSTRAINT FK_PROJECT_COLLABORATORS_USER
            REFERENCES SKYROOF.USER_TABLE,
    PRIMARY KEY (FK_PROJECT, FK_USER)
);

CREATE TABLE SKYROOF.TASK
(
    TASK_ID        NUMBER(19)    NOT NULL PRIMARY KEY,
    TITLE          VARCHAR2(150) NOT NULL,
    DESCRIPTION    VARCHAR2(2000),
    STATE          VARCHAR2(50)  NOT NULL,
    CREATOR_ID     NUMBER(19)    NOT NULL
        CONSTRAINT FK_TASK_CREATOR
            REFERENCES SKYROOF.USER_TABLE,
    CREATION_DATE  TIMESTAMP(6)  NOT NULL,
    START_DATE     TIMESTAMP(6),
    COMPLETED_DATE TIMESTAMP(6),
    PROJECT_ID     NUMBER(19)    NOT NULL
        CONSTRAINT FK_TASK_PROJECT
            REFERENCES SKYROOF.PROJECT
);

CREATE TABLE SKYROOF.REVINFO
(
    REV      NUMBER(10) NOT NULL PRIMARY KEY,
    REVTSTMP NUMBER(19)
);

CREATE TABLE SKYROOF.PROJECT_AUD
(
    PROJECT_ID  NUMBER(19) NOT NULL,
    REV         NUMBER(10) NOT NULL
        CONSTRAINT FK_PROJECT_AUD_REVINFO
            REFERENCES SKYROOF.REVINFO,
    REVTYPE     NUMBER(3),
    DESCRIPTION VARCHAR2(2000),
    IS_DELETED  NUMBER(1),
    TITLE       VARCHAR2(150),
    OWNER_ID    NUMBER(19),
    PRIMARY KEY (PROJECT_ID, REV)
);

CREATE TABLE SKYROOF.PROJECT_COLLABORATORS_AUD
(
    REV        NUMBER(10) NOT NULL
        CONSTRAINT FK_PROJECT_COLLABORATORS_REVINFO
            REFERENCES SKYROOF.REVINFO,
    FK_PROJECT NUMBER(19) NOT NULL,
    FK_USER    NUMBER(19) NOT NULL,
    REVTYPE    NUMBER(3),
    PRIMARY KEY (REV, FK_PROJECT, FK_USER)
);

CREATE TABLE SKYROOF.TASK_AUD
(
    TASK_ID        NUMBER(19) NOT NULL,
    REV            NUMBER(10) NOT NULL
        CONSTRAINT FK_TASK_AUD_REVINFO
            REFERENCES SKYROOF.REVINFO,
    REVTYPE        NUMBER(3),
    COMPLETED_DATE TIMESTAMP(6),
    DESCRIPTION    VARCHAR2(2000),
    START_DATE     TIMESTAMP(6),
    STATE          VARCHAR2(50),
    TITLE          VARCHAR2(150),
    CREATOR_ID     NUMBER(19),
    PROJECT_ID     NUMBER(19),
    PRIMARY KEY (TASK_ID, REV)
);

CREATE SEQUENCE "SKYROOF"."HIBERNATE_SEQUENCE" INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE "SKYROOF"."PROJECT_ID_SEQUENCE" INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE "SKYROOF"."TASK_ID_SEQUENCE" INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
CREATE SEQUENCE "SKYROOF"."USER_ID_SEQUENCE" INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;